# https://taskfile.dev

version: '3'

silent: true

tasks:
  build:
    desc: Build the templated files
    cmds:
      - "../temingo/temingo{{ .EXTENSION }} -values values.yaml -inputDir . -partialsDir partials -outputDir output -templateFileExtension .html.template -partialFileExtension .template -generatedFileExtension .html"
    vars:
      EXTENSION: '{{ if eq OS "windows" }}.exe{{ end }}'

  serve:
    desc: Serve the generated files locally
    dir: output
    cmds:
      - "../../serve/serve{{ .EXTENSION }}"
    vars:
      EXTENSION: '{{ if eq OS "windows" }}.exe{{ end }}'
