title: example-website

css:

  generalsize: 1em # size of elements
  fontsize: 0.9em

  colors:
    primaryColor:
      hue: 0
      saturation: 100%
      lightness: 43%
      alpha: 1
    
    primaryBgColor:
      hue: 60
      saturation: 100%
      lightness: 27%
      alpha: 1

    secondaryColor:
      hue: 240
      saturation: 100%
      lightness: 43%
      alpha: 1
    
    secondaryBgColor:
      hue: 120
      saturation: 100%
      lightness: 43%
      alpha: 1
    
    siteColor:
      hue: 0
      saturation: 0%
      lightness: 10%
      alpha: 1
    siteBgColor:
      hue: 0
      saturation: 0%
      lightness: 90%
      alpha: 1

    buttonColor:
      hue: 0
      saturation: 0%
      lightness: 10%
      alpha: 1
    buttonBgColor:
      hue: 0
      saturation: 0%
      lightness: 90%
      alpha: 1
    
    borderColor:
      hue: 0
      saturation: 0%
      lightness: 20%
      alpha: 1

  borders:
    radius: 5px
    width: 2px
  
  animations:
    transitionDuration: 0.2s

  navigation:
    padding: 0.8em

factors:
  icons: 1.7
  sizes:
    regular: 0.8
    large: 1
    big: 1.2
